Traceback (most recent call last):
  File "requester.py", line 33, in <module>
    send_requests("stackoverflow.com")
  File "requester.py", line 23, in send_requests
    for j in search(q+f" site:{site}", tld="co.in", num=5, stop=5, pause=2):
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\site-packages\googlesearch\__init__.py", line 305, in search
    html = get_page(url, user_agent, verify_ssl)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\site-packages\googlesearch\__init__.py", line 174, in get_page
    response = urlopen(request)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\ProgramData\Anaconda3\envs\fizyka\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
